### ISSUE TITLE
generated script name always prepended by numbers

### ISSUE THREAD

**Issue by iliekdags** [lexich/gulp-image-preload#1]
If you have your gulpfile set up correctly there isn't much reason for appending numbers to the generated script. I don't understand why you don't just use the path we provide for the generated script? I want it to always go to www/preloader.js not www/653808.preloader.js

Maybe I'm missing something and the docs just need to be updated to be more obvious as how to do this?

**Comment by lexich** [comment]
If you don't like to use revision prefix, try to set `md5` option to `false`

**Comment by wesleyahall** [comment]
I figured this out -- I guess the docs just weren't very clear as to what was happening there. Thanks though! :)
